CREATE DEFINER=`Matti`@`localhost` PROCEDURE `ShowProcedures`()
BEGIN
SELECT ROUTINE_SCHEMA AS Db, ROUTINE_NAME AS Name, ROUTINE_TYPE AS Type
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = DATABASE();
END